server:
  port: 8080
spring:
  activemq:
    broker-url: tcp://192.168.3.30:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true   # false = Queue ,true = Topic

# 自己定义的队列名称
myqueue: boot-activemq-queue
# 自己定义的主题名称
mytopic: boot-activemq-topic
