server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置 Sentinel dashborad 地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始一次扫描，直到找到未被占用的端口
        port: 8719

service-url:
  nacos-user-service: http://nacos-payment-provider

# 激活 sentinel 对 openfeign 的支持
feign:
  sentinel:
    enabled: true


