server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-calss-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.216.0:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql123456

eureka:
  client:
    #表示是否将自己注册到EurekaServer，默认是true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ibbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包